apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: prometheus
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: stable/prometheus-operator
    repoURL: https://github.com/helm/charts
    targetRevision: HEAD
